---
- hosts: localhost
  become: yes
  connection: ssh
  user: ansible

  tasks:
    - name: installing httpd
      command: yum install httpd -y

    - name: restarting httpd
      service: name=httpd state=restarted
